@startuml
skinparam linetype poly

skinparam rectangle {
    backgroundColor LightGrey
}

rectangle <<Out Of Scope>> {
    package "Server" {
        () TCP

        TCP - [Backend]
    }

    package "Browser" {
        TCP <-- [Networking]: "WebAuthn"
        [CTAP Interface] as ctapi
    }
}

package "OS" {
    [USB Socket]

    database "TPM" as tpm
}

package "Hardware Authenticators" {
    component Authenticator
    Authenticator <---> OS
}

package "Soft Token Application" {
    () TCP as TCP2
    [Biometrics] as bio
    [CTAP Connector] as conn
    [CBOR Converter] as cbor
    [Key Management]  as km
    database "Secure Safe" as db
    [GUI] as GUI
    [Monitoring] as mon
}

package "Drivers" {
    [USB Driver]        <-down-> [USB Socket]
    [Logging]
}


Networking <-> ctapi
ctapi <--> OS

GUI -down-> km
GUI <--> conn
GUI -> mon
GUI -> cbor
mon -> [Logging]
conn -down- TCP2
conn -> km
conn -> cbor
km --> db
km --> tpm

[USB Driver] -> [Logging]
TCP2 <--> [USB Driver]



@enduml